# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HeliportRiskAnalysis(object):
    def setupUi(self, HeliportRiskAnalysis):
        HeliportRiskAnalysis.setObjectName("HeliportRiskAnalysis")
        HeliportRiskAnalysis.resize(961, 875)
        HeliportRiskAnalysis.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        HeliportRiskAnalysis.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        HeliportRiskAnalysis.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(HeliportRiskAnalysis)
        self.centralwidget.setObjectName("centralwidget")
        self.Enter = QtWidgets.QPushButton(self.centralwidget)
        self.Enter.setGeometry(QtCore.QRect(180, 50, 75, 23))
        self.Enter.setObjectName("Enter")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(290, 10, 41, 701))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.StateTextBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.StateTextBox.setGeometry(QtCore.QRect(70, 50, 91, 21))
        self.StateTextBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StateTextBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.StateTextBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.StateTextBox.setObjectName("StateTextBox")
        self.InformationLabel_1 = QtWidgets.QLabel(self.centralwidget)
        self.InformationLabel_1.setGeometry(QtCore.QRect(40, 20, 241, 16))
        self.InformationLabel_1.setObjectName("InformationLabel_1")
        self.InformationLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.InformationLabel_2.setGeometry(QtCore.QRect(40, 90, 241, 16))
        self.InformationLabel_2.setObjectName("InformationLabel_2")
        self.InformationLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.InformationLabel_3.setGeometry(QtCore.QRect(360, 140, 371, 16))
        self.InformationLabel_3.setObjectName("InformationLabel_3")
        self.InformationLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.InformationLabel_4.setGeometry(QtCore.QRect(360, 90, 241, 16))
        self.InformationLabel_4.setObjectName("InformationLabel_4")
        self.FAALogo = QtWidgets.QLabel(self.centralwidget)
        self.FAALogo.setGeometry(QtCore.QRect(880, 10, 61, 31))
        self.FAALogo.setText("")
        self.FAALogo.setPixmap(QtGui.QPixmap("Helicopter_Logo.png"))
        self.FAALogo.setScaledContents(True)
        self.FAALogo.setObjectName("FAALogo")
        self.RiskLabel = QtWidgets.QLabel(self.centralwidget)
        self.RiskLabel.setGeometry(QtCore.QRect(590, 90, 121, 16))
        self.RiskLabel.setAutoFillBackground(False)
        self.RiskLabel.setObjectName("RiskLabel")
        self.List1 = QtWidgets.QListWidget(self.centralwidget)
        self.List1.setGeometry(QtCore.QRect(30, 120, 256, 371))
        self.List1.setObjectName("List1")
        self.ObstacleList = QtWidgets.QTableWidget(self.centralwidget)
        self.ObstacleList.setGeometry(QtCore.QRect(400, 530, 461, 181))
        self.ObstacleList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ObstacleList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.ObstacleList.setObjectName("ObstacleList")
        self.ObstacleList.setColumnCount(3)
        self.ObstacleList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ObstacleList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ObstacleList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ObstacleList.setHorizontalHeaderItem(2, item)
        self.ObstacleList.horizontalHeader().setSortIndicatorShown(False)
        self.InformationLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.InformationLabel_5.setGeometry(QtCore.QRect(360, 50, 101, 16))
        self.InformationLabel_5.setObjectName("InformationLabel_5")
        self.InformationLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.InformationLabel_7.setGeometry(QtCore.QRect(360, 70, 111, 16))
        self.InformationLabel_7.setObjectName("InformationLabel_7")
        self.InformationLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.InformationLabel_8.setGeometry(QtCore.QRect(360, 30, 101, 16))
        self.InformationLabel_8.setObjectName("InformationLabel_8")
        self.LatLongLabel = QtWidgets.QLabel(self.centralwidget)
        self.LatLongLabel.setGeometry(QtCore.QRect(480, 70, 171, 16))
        self.LatLongLabel.setAutoFillBackground(False)
        self.LatLongLabel.setObjectName("LatLongLabel")
        self.NavIDLabel = QtWidgets.QLabel(self.centralwidget)
        self.NavIDLabel.setGeometry(QtCore.QRect(480, 50, 171, 16))
        self.NavIDLabel.setAutoFillBackground(False)
        self.NavIDLabel.setObjectName("NavIDLabel")
        self.HeliportnameLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeliportnameLabel.setGeometry(QtCore.QRect(480, 30, 171, 16))
        self.HeliportnameLabel.setAutoFillBackground(False)
        self.HeliportnameLabel.setObjectName("HeliportnameLabel")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(60, 750, 801, 23))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webEngineView.setGeometry(QtCore.QRect(330, 160, 601, 331))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        HeliportRiskAnalysis.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HeliportRiskAnalysis)
        self.statusbar.setObjectName("statusbar")
        HeliportRiskAnalysis.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(HeliportRiskAnalysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 26))
        self.menubar.setObjectName("menubar")
        HeliportRiskAnalysis.setMenuBar(self.menubar)

        self.retranslateUi(HeliportRiskAnalysis)
        QtCore.QMetaObject.connectSlotsByName(HeliportRiskAnalysis)

    def retranslateUi(self, HeliportRiskAnalysis):
        _translate = QtCore.QCoreApplication.translate
        HeliportRiskAnalysis.setWindowTitle(_translate("HeliportRiskAnalysis", "Heliport Risk Analysis "))
        self.Enter.setText(_translate("HeliportRiskAnalysis", "Enter"))
        self.StateTextBox.setPlainText(_translate("HeliportRiskAnalysis", "Enter State"))
        self.InformationLabel_1.setText(_translate("HeliportRiskAnalysis", "Enter State Abbreviation:"))
        self.InformationLabel_2.setText(_translate("HeliportRiskAnalysis", "Select a Heliport Below:"))
        self.InformationLabel_3.setText(_translate("HeliportRiskAnalysis", "Obstacles within 1nm of the selected helipad location:"))
        self.InformationLabel_4.setText(_translate("HeliportRiskAnalysis", "Estimated Risk based on Obstacle Data:"))
        self.RiskLabel.setText(_translate("HeliportRiskAnalysis", "N/A"))
        item = self.ObstacleList.horizontalHeaderItem(0)
        item.setText(_translate("HeliportRiskAnalysis", "Obstacle"))
        item = self.ObstacleList.horizontalHeaderItem(1)
        item.setText(_translate("HeliportRiskAnalysis", "Distance(nm)"))
        item = self.ObstacleList.horizontalHeaderItem(2)
        item.setText(_translate("HeliportRiskAnalysis", "Height(AGL)"))
        self.InformationLabel_5.setText(_translate("HeliportRiskAnalysis", "Heliport NavID:"))
        self.InformationLabel_7.setText(_translate("HeliportRiskAnalysis", "Latitude/Longitude:"))
        self.InformationLabel_8.setText(_translate("HeliportRiskAnalysis", "Heliport Name:"))
        self.LatLongLabel.setText(_translate("HeliportRiskAnalysis", "N/A"))
        self.NavIDLabel.setText(_translate("HeliportRiskAnalysis", "N/A"))
        self.HeliportnameLabel.setText(_translate("HeliportRiskAnalysis", "N/A"))

from PyQt5 import QtWebEngineWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HeliportRiskAnalysis = QtWidgets.QMainWindow()
    ui = Ui_HeliportRiskAnalysis()
    ui.setupUi(HeliportRiskAnalysis)
    HeliportRiskAnalysis.show()
    sys.exit(app.exec_())

